apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: gitlab-confluent
  name: gitlab-confluent
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: gitlab-lambda-broker

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: GitLabSource
        metadata:
          name: gitlab-confluent-demo
        spec:
          accessToken:
            secretKeyRef:
              key: accessToken
              name: gitlabsecret
          eventTypes:
          - push_events
          projectUrl: 'https://gitlab.com/sebgoa/kdemo'
          secretToken:
            secretKeyRef:
              key: secretToken
              name: gitlabsecret
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: gitlab-lambda-broker

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: aws-lambda-trigger
        spec:
          broker: gitlab-lambda-broker
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: AWSTarget
              name: aws-lambda-dumper

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: confluent-trigger
        spec:
          broker: gitlab-lambda-broker
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ConfluentTarget
              name: confluent-demo

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: AWSTarget
        metadata:
          name: aws-lambda-dumper
        spec:
          awsApiKey:
            secretKeyRef:
              name: awscreds
              key: aws_access_key_id
          awsApiSecret:
            secretKeyRef:
              name: awscreds
              key: aws_secret_access_key
          lambda:
            arn: arn:aws:lambda:us-east-1:587264368683:function:message-dumper

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ConfluentTarget
        metadata:
          name: confluent-demo
        spec:
          topic: gitlab-records
          securityprotocol: SASL_SSL
          saslmechanism: PLAIN
          bootstrapservers: pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
          username:
            secretKeyRef:
              name: confluent
              key: username
          password:
            secretKeyRef:
              name: confluent
              key: password
