apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: sqs-twilio
  name: sqs-twilio
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: events-aws

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: transform-sqs
            
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: AWSSQSSource
        metadata:
          name: sample
        spec:
          arn: arn:aws:sqs:us-west-2:123456789012:triggermeshtest
          credentials:
            accessKeyID:
              valueFromSecret:
                name: awscreds
                key: aws_access_key_id
            secretAccessKey:
              valueFromSecret:
                name: awscreds
                key: aws_secret_access_key
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-aws
             
    - object:
        apiVersion: messaging.knative.dev/v1beta1
        kind: Subscription
        metadata:
          name: event-twilio
        spec:
          channel:
            apiVersion: messaging.knative.dev/v1beta1
            kind: InMemoryChannel
            name: events-aws-kne-trigger
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: trans-twilio
          reply:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: transform-sqs

    - object:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        metadata:
          name: trans-twilio
          labels:
            serving.knative.dev/visibility: cluster-local
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/triggermesh/transtwilio:v0.0.13

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          labels:
            eventing.knative.dev/broker: text-message-hub
          name: sendme-twilio
        spec:
          broker: transform-sqs
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: TwilioTarget
              name: twilio-sqs-sms

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: TwilioTarget
        metadata:
          name: twilio-sqs-sms
        spec:
          defaultPhoneTo: "+19998887777"
          defaultPhoneFrom: "+125666666"
          sid:
            secretKeyRef:
              name: twilio
              key: sid
          token:
            secretKeyRef:
              name: twilio
              key: token


