apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: tekton-test
spec:
  params:
    - name: greeting
      type: string
      description: Who are we saying hello to
  steps:
  - args:
    - Hello
    - world
    - $(params.greeting)
    command:
    - echo
    image: centos
    name: first-action
    resources: {}
