apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: oracledb-fn-baseline
  name: oraclesource-oraclecloudtarget
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: events-oracle

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: oracle-source
        spec:
          template:
            spec:
              containers:
              - image: docker.io/cab105/oracle-source:latest

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: SinkBinding
        metadata:
          name: bind-oracle-source
        spec:
          subject:
            apiVersion: serving.knative.dev/v1
            kind: Service
            name: oracle-source

          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-oracle
          ceOverrides:
            extensions:
              sink: bound

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: OracleTarget
        metadata:
          name: oracle-dumper
        spec:
          oracleApiPrivateKey:
            secretKeyRef:
              name: oraclecreds
              key: apiKey
          oracleApiPrivateKeyPassphrase:
            secretKeyRef:
              name: oraclecreds
              key: apiPassphrase
          oracleApiPrivateKeyFingerprint:
            secretKeyRef:
              name: oraclecreds
              key: apiKeyFingerprint
          oracleTenancy: ocid1.tenancy.oc1..aaaaaaaaav23f45mqyxmwu4x3s2uhuh4rb2bwdpgb5kbpjqvwiiqufhsq6za
          oracleUser: ocid1.user.oc1..aaaaaaaacaxtveoy4zx7rsg7lanexmouxjxay6godthrfsocpl6ggrfpbiuq
          oracleRegion: us-phoenix-1
          function:
            function: ocid1.fnfunc.oc1.phx.aaaaaaaaaajrgy4on66e6krko73h2im5qaiiagecg5hmbcqib2kpbzlcy3bq

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          name: oracle-fn-dumper-target-trigger
          labels:
            eventing.knative.dev/broker: events-oracle
        spec:
          broker: events-oracle
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: OracleTarget
              name: oracle-dumper

