apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: oracledb-fn-translated
  name: oraclesource-oraclecloudtarget
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: events-oracle

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: transform-oracle

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: oracle-source
        spec:
          template:
            spec:
              containers:
              - image: docker.io/cab105/oracle-source:latest

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: event-display
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/triggermesh/event_display-864884f202126ec3150c5fcef437d90c@sha256:5b0491983fa2019ab0fd7b8e5eaafb0bf9df3cf6fd4d1e4f10a34fcc6b59e858
                name: user-container

    - object:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        metadata:
          name: trans-oracle
          labels:
            serving.knative.dev/visibility: cluster-local
        spec:
          template:
            spec:
              containers:
              - image: docker.io/cab105/transoracle:latest

    - object:
        apiVersion: messaging.knative.dev/v1beta1
        kind: Subscription
        metadata:
          name: event-oracle-cloud
        spec:
          channel:
            apiVersion: messaging.knative.dev/v1beta1
            kind: InMemoryChannel
            name: events-oracle-kne-trigger
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: trans-oracle
          reply:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: transform-oracle

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: SinkBinding
        metadata:
          name: bind-oracle-source
        spec:
          subject:
            apiVersion: serving.knative.dev/v1
            kind: Service
            name: oracle-source
            namespace: cab

          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-oracle
          ceOverrides:
            extensions:
              sink: bound

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: OracleTarget
        metadata:
          name: oracle-fn-dumper-target
        spec:
          oracleApiPrivateKey:
            secretKeyRef:
              name: oraclecreds
              key: apiKey
          oracleApiPrivateKeyPassphrase:
            secretKeyRef:
              name: oraclecreds
              key: apiPassphrase
          oracleApiPrivateKeyFingerprint:
            secretKeyRef:
              name: oraclecreds
              key: apiKeyFingerprint
          oracleTenancy: ocid1.tenancy.oc1..aaaaaaaaav23f45mqyxmwu4x3s2uhuh4rb2bwdpgb5kbpjqvwiiqufhsq6za
          oracleUser: ocid1.user.oc1..aaaaaaaacaxtveoy4zx7rsg7lanexmouxjxay6godthrfsocpl6ggrfpbiuq
          oracleRegion: us-phoenix-1
          function:
            function: ocid1.fnfunc.oc1.phx.aaaaaaaaaajrgy4on66e6krko73h2im5qaiiagecg5hmbcqib2kpbzlcy3bq

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          name: oracle-fn-dumper-target-trigger
          labels:
            eventing.knative.dev/broker: transform-oracle
        spec:
          broker: transform-oracle
          filter:
            attributes:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: trans-oracle
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: OracleTarget
              name: oracle-fn-dumper-target

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          name: oracle-fn-dumper-target-trigger
          labels:
            eventing.knative.dev/broker: transform-oracle
        spec:
          broker: transform-oracle
          filter:
            attributes:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: OracleTarget
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: event-display

