apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: github-display
  name: github-display
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: github-default

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: GitHubSource
        metadata:
           name: github-source
        spec:
          accessToken:
            secretKeyRef:
              key: accessToken
              name: githubsecret
          eventTypes:
          - push
          ownerAndRepository: sebgoa/tmserverless
          secretToken:
            secretKeyRef:
              key: secretToken
              name: githubsecret
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: github-default

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: event-display
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a4c088d4e48eaac7dc6de0dc3ef3fa4ed3e8f224baa4c2937f11061d380df430
                name: user-container

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          labels:
            eventing.knative.dev/broker: text-message-hub
          name: sendme-github
        spec:
          broker: github-default
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: event-display
