apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: kafka-display
  name: kafka-display
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name: kafka

    - object:
        apiVersion: sources.knative.dev/v1beta1
        kind: KafkaSource
        metadata:
          name: kafka-topic1
        spec:
          consumerGroup: consumers-group1
          bootstrapServers:
          - mycluster-kafka-bootstrap.kafka:9092
          topics:
          - mytopic
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1
              kind: Broker
              name: kafka

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: event-display
        spec:
          template:
            spec:
              containers:
              - image:  gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:46d5a66f300c3ced590835d379a0e9badf413ae7ab60f21a2550ecedbc9eb9d3
                name: user-container

    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: kafka-events
        spec:
          broker: kafka
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: event-display
