apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: slack-confluent
  name: slack-confluent
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: slack

    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: SlackSource
        metadata:
          name: triggermesh-slack-bot
        spec:
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: slack

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: slack-confluent
        spec:
          broker: slack
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ConfluentTarget
              name: confluent-demo

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ConfluentTarget
        metadata:
          name: confluent-demo
        spec:
          topic: <KAFKA-TOPIC>
          securityProtocol: SASL_SSL
          saslMechanism: PLAIN
          bootstrapServers:
            - <CONFLUENT-HOST:CONFLUENT-PORT>
          username: <USERNAME>
          password:
            secretKeyRef:
              name: confluent
              key: password
