apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: oracle-bridge-zendesk-aws-demo
  name: oracle-bridge-zendesk-aws-demo
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: events-oracle

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: oracle-source
        spec:
          template:
            spec:
              containers:
              - image: docker.io/cab105/oracle-source:latest

    - object:
        apiVersion: serving.knative.dev/v1alpha1
        kind: Service
        metadata:
          name: trans-oracle
          labels:
            serving.knative.dev/visibility: cluster-local
        spec:
          template:
            spec:
              containers:
              - image: docker.io/cab105/oracledemotrans-zendesk:latest

    - object:
        apiVersion: messaging.knative.dev/v1beta1
        kind: Subscription
        metadata:
          name: event-oracle-cloud
        spec:
          channel:
            apiVersion: messaging.knative.dev/v1beta1
            kind: InMemoryChannel
            name: events-oracle-kne-trigger
          subscriber:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: trans-oracle
          reply:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-oracle

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: SinkBinding
        metadata:
          name: bind-oracle-source
        spec:
          subject:
            apiVersion: serving.knative.dev/v1
            kind: Service
            name: oracle-source
            namespace: cab
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-oracle
          ceOverrides:
            extensions:
              sink: bound

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: AWSTarget
        metadata:
          name: aws-lambda-dumper-target
        spec:
          awsApiKey:
            secretKeyRef:
              name: awscreds
              key: AWS_ACCESS_KEY_ID
          awsApiSecret:
            secretKeyRef:
              name: awscreds
              key: AWS_SECRET_ACCESS_KEY
          lambda:
            arn: arn:aws:lambda:us-west-2:043455440429:function:lambdadumper
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: events-oracle
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ZendeskTarget
        metadata:
          name: tm-zendesk-target
        spec:
          subject: Dogstore reorder request
          subdomain: dogstore
          email: fulfillment@dogstore.com
          token:
             secretKeyRef:
               name: zendesk
               key: token

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          name: aws-lambda-dumper-target
          labels:
            eventing.knative.dev/broker: events-oracle
        spec:
          broker: events-oracle
          filter:
            attributes:
              type: com.triggermesh.targets.oracle.function.dogstore-neworder
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: AWSTarget
              name: aws-lambda-dumper-target

    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          name: zendesk-target-trigger
          labels:
            eventing.knative.dev/broker: events-oracle
        spec:
          broker: events-oracle
          filter:
            attributes:
              type: com.triggermesh.targets.zendesk
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ZendeskTarget
              name: tm-zendesk-target