apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: kafka-elasticsearch
  name: kafka-elasticsearch
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        metadata:
          name: kafka

    - object:
        apiVersion: sources.knative.dev/v1beta1
        kind: KafkaSource
        metadata:
          name: kafka-topic1
        spec:
          consumerGroup: consumers-group1
          bootstrapServers:
          - mycluster-kafka-bootstrap.kafka:9092
          topics:
          - mytopic
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1
              kind: Broker
              name: kafka

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ElasticsearchTarget
        metadata:
          name: tm-elastic
        spec:
          connection:
            addresses:
              - https://triggermesh-demo-es-http.tm-elastic:9200
            skipVerify: true
            username: elastic
            password:
              secretKeyRef:
                key: password
                name: elastic
          indexName: tmindex

    - object:
        apiVersion: eventing.knative.dev/v1
        kind: Trigger
        metadata:
          name: kafka-elasticsearch
        spec:
          broker: kafka
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ElasticsearchTarget
              name: tm-elastic
