apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: gitlab-awslambda
  name: gitlabsource-awslambdatarget
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: gitlab-lambda-broker

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: GitLabSource
        metadata:
            finalizers:
                - gitlabsources.sources.knative.dev
            name: gitlab-sample-source
        spec:
            accessToken:
                secretKeyRef:
                    key: accessToken
                    name: gitlabcreds
            eventTypes:
                - push_events
            projectUrl: 'https://gitlab.com/cab105/testproj'
            secretToken:
                secretKeyRef:
                    key: secretToken
                    name: gitlabcreds
            sink:
                ref:
                    apiVersion: eventing.knative.dev/v1alpha1
                    kind: Broker
                    name: gitlab-lambda-broker

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: AWSTarget
        metadata:
          name: aws-lambda-dumper-target
        spec:
          awsApiKey:
            secretKeyRef:
              name: awscreds
              key: AWS_ACCESS_KEY_ID
          awsApiSecret:
            secretKeyRef:
              name: awscreds
              key: AWS_SECRET_ACCESS_KEY
          lambda:
            arn: arn:aws:lambda:us-west-2:043455440429:function:lambdadumper

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: aws-lambda-dumper-trigger
        spec:
          broker: gitlab-lambda-broker
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: AWSTarget
              name: aws-lambda-dumper-target
