# Copyright (c) 2020 TriggerMesh Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: gitlab-kinesis
  name: gitlabsource-awskinesistarget
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: gitlab-kinesis-broker

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: GitLabSource
        metadata:
            finalizers:
                - gitlabsources.sources.knative.dev
            name: gitlab-sample-source
        spec:
            accessToken:
                secretKeyRef:
                    key: accessToken
                    name: gitlabcreds
            eventTypes:
                - push_events
            projectUrl: 'https://gitlab.com/cab105/testproj'
            secretToken:
                secretKeyRef:
                    key: secretToken
                    name: gitlabcreds
            sink:
                ref:
                    apiVersion: eventing.knative.dev/v1alpha1
                    kind: Broker
                    name: gitlab-kinesis-broker

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: AWSTarget
        metadata:
          name: aws-kinesis-target
        spec:
          awsApiKey:
            secretKeyRef:
              name: awscreds
              key: AWS_ACCESS_KEY_ID
          awsApiSecret:
            secretKeyRef:
              name: awscreds
              key: AWS_SECRET_ACCESS_KEY
          kinesis:
            arn: arn:aws:kinesis:us-west-2:043455440429:stream/cabtest
            partition: 1

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: aws-kinesis-dumper-trigger
        spec:
          broker: gitlab-kinesis-broker
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: AWSTarget
              name: aws-kinesis-target
