apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  name: &bridgename azureactivitylogs-splunk
  annotations:
    bridges.triggermesh.io/name: *bridgename
spec:
  components:

    # Event broker
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: &brokername events

    # Event source
    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: AzureActivityLogsSource
        metadata:
          name: activitylogs
        spec:
          eventHubsSASPolicyID: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/authorizationRules/{authorizationRuleName}
          auth:
            servicePrincipal:
              clientID:
                value: '{clientId}'
              clientSecret:
                value: '{clientSecret}'
              tenantID:
                value: '{tenantId}'
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: *brokername

    # Event target 
    - object:
        apiVersion: eventing.knative.dev/v1alpha1
        kind: Trigger
        metadata:
          name: &targetname splunk
        spec:
          broker: *brokername
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: SplunkTarget
              name: *targetname
    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: SplunkTarget
        metadata:
          name: *targetname
        spec:
          endpoint: '{endpointUrl}'
          token:
            valueFromSecret:
              name: '{secret}'
              key: token
