apiVersion: v1
kind: Secret
metadata:
  name: githubsecret
type: Opaque
stringData:
  accessToken: ''
  secretToken: ''
---
apiVersion: v1
kind: Secret
metadata:
  name: googlesheet
type: Opaque
stringData:
  credentials: |-
''

---
apiVersion: v1
kind: Secret
metadata:
  name: slacktarget
type: Opaque
stringData:
  token: ''

