apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/description: ""
    bridges.triggermesh.io/name: harmless-link
  name: zendesk-flow
spec:
  components:
  - object:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      metadata:
        name: default
    options:
      enableResync: false
  - object:
      apiVersion: sources.knative.dev/v1alpha2
      kind: PingSource
      metadata:
        name: foobar
      spec:
        jsonData: '{"foo": "bar"}'
        schedule: '*/1 * * * *'
        sink:
          ref:
            apiVersion: eventing.knative.dev/v1alpha1
            kind: Broker
            name: default
    options:
      enableResync: false
  - object:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Trigger
      metadata:
        name: zendesk
      spec:
        broker: default
        subscriber:
          ref:
            apiVersion: targets.triggermesh.io/v1alpha1
            kind: ZendeskTarget
            name: foobarzendesk
  - object:
      apiVersion: targets.triggermesh.io/v1alpha1
      kind: ZendeskTarget
      metadata:
        name: foobarzendesk
      spec:
        email: jeff@triggermesh.com
        subdomain: tmdev1
        subject: hey what is going on
        token:
          secretKeyRef:
            key: token
            name: zendesk
    options:
      enableResync: false
