apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  name: oraclesource-awslambdatarget
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: oracle-lambda-broker

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: oracle-source
        spec:
          template:
            spec:
              containers:
              - image: docker.io/cab105/oracle-source:latest

    - object:
        apiVersion: sources.knative.dev/v1alpha1
        kind: SinkBinding
        metadata:
          name: oracle-source-binding
        spec:
          subject:
            apiVersion: serving.knative.dev/v1
            kind: Service
            name: oracle-source
        sink:
          ref:
            apiVersion: eventing.knative.dev/v1beta1
            kind: Broker
            name: oracle-lambda-broker

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: AWSTarget
        metadata:
          name: aws-lambda-dumper-target
        spec:
          awsApiKey:
            secretKeyRef:
              name: awscreds
              key: AWS_ACCESS_KEY_ID
          awsApiSecret:
            secretKeyRef:
              name: awscreds
              key: AWS_SECRET_ACCESS_KEY
          lambda:
            arn: arn:aws:lambda:us-west-2:043455440429:function:lambdadumper

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: aws-lambda-dumper-trigger
        spec:
          broker: oracle-lambda-broker
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: AWSTarget
              name: aws-lambda-dumper-target
