apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  name: slack-elastic
spec:
  components:
    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Broker
        metadata:
          name: slack

    - object:
        apiVersion: sources.triggermesh.io/v1alpha1
        kind: SlackSource
        metadata:
          name: triggermesh-knbot
        spec:
          slackToken:
            secretKeyRef:
              name: slack
              key: token
          threadiness: 1
          sink:
            ref:
              apiVersion: eventing.knative.dev/v1beta1
              kind: Broker
              name: slack

    - object:
        apiVersion: targets.triggermesh.io/v1alpha1
        kind: ElasticsearchTarget
        metadata:
          name: tm-elastic
        spec:
          connection:
            addresses:
              - https://triggermesh-demo-es-http.tm-elastic:9200
            skipVerify: true
            username: elastic
            password:
              secretKeyRef:
                key: password
                name: elastic
          indexName: tmindex

    - object:
        apiVersion: eventing.knative.dev/v1beta1
        kind: Trigger
        metadata:
          name: slack-elastic-trigger
        spec:
          broker: slack
          subscriber:
            ref:
              apiVersion: targets.triggermesh.io/v1alpha1
              kind: ElasticsearchTarget
              name: tm-elastic
