apiVersion: flow.triggermesh.io/v1alpha1
kind: Bridge
metadata:
  annotations:
    bridges.triggermesh.io/name: pingsource-display
  name: pingsource-display
spec:
  components:
    - object:
        apiVersion: sources.knative.dev/v1alpha2
        kind: PingSource
        metadata:
          name: cron-job-source-tm
        spec:
          schedule: "*/1 * * * *"
          jsonData: '{"message": "let the event be dispatched"}'
          sink:
            ref:
              apiVersion: serving.knative.dev/v1
              kind: Service
              name: event-display

    - object:
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: event-display
        spec:
          template:
            spec:
              containers:
              - image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a4c088d4e48eaac7dc6de0dc3ef3fa4ed3e8f224baa4c2937f11061d380df430
                name: user-container
